name: Run Discord Bot

on:
  schedule:
    - cron: "30 1 * * *"   # 8h30 sáng VN (1h30 UTC)
    - cron: "30 13 * * *"  # 8h30 tối VN (13h30 UTC)
  workflow_dispatch:       # cho phép chạy thủ công

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install python-dotenv

      - name: Create configs directory
        run: mkdir -p configs

      - name: Create .env file
        run: |
          echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" >> .env
          echo "FIREBASE_CREDENTIALS=${{ secrets.FIREBASE_CREDENTIALS }}" >> .env
          echo "FIREBASE_CONFIG_JSON=${{ secrets.FIREBASE_CONFIG_JSON }}" >> .env
          echo "FLASK_SECRET_KEY=${{ secrets.FLASK_SECRET_KEY }}" >> .env

      - name: Run bot for 10 minutes
        run: |
          timeout 600 python src/main.py
